# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
        with:
          path: image
      - 
        name: List files in the repository
        run: |   
          ls -al image/
          cat image/.git/refs/heads/master
      - 
        name: Set the tag for the image to a global variable
        id: set_tag
        run: |
          IMAGE_VESION=`cat image/version`
          IMAGE_REFS=`cat image/.git/refs/heads/master`
          echo "::set-output name=IMAGE_VERSION::$IMAGE_VERSION"
          echo "::set-output name=IMAGE_REFS::$IMAGE_REFS"
      - 
        name: Check a global variable
        run: |   
          echo ${{ steps.set_tag.outputs.IMAGE_VERSION }}
          echo ${{ steps.set_tag.outputs.IMAGE_REFS }}
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: image/.
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/githubtest:latest
            ${{ secrets.DOCKER_USERNAME }}/githubtest:${{ steps.set_tag.outputs.IMAGE_VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/githubtest:${{ steps.set_tag.outputs.IMAGE_REFS }}
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - 
        name: Checkout other repo
        uses: actions/checkout@v2
        with:
          repository: tbuchi888/argocd_sample_repo
          path: argo_repo
      - 
        name: List files in the repository
        run: |
          echo "--- image ---"
          ls image/
          echo "--- argo_repo ---"
          ls argo_repo/
