# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
        with:
          path: image
      - 
        name: List files in the repository
        run: |   
          ls -al image/
          cat image/.git/refs/heads/master
          echo ${{ github.sha }}
      - 
        name: Set the tag for the image to a global variable
        id: set_tag
        run: |
          IMAGE_VERSION=`cat image/version`
          echo "::set-output name=IMAGE_VERSION::$IMAGE_VERSION"
      - 
        name: Check a global variable
        run: |   
          echo ${{ steps.set_tag.outputs.IMAGE_VERSION }}
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: image/.
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/githubtest:latest
            ${{ secrets.DOCKER_USERNAME }}/githubtest:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/githubtest:${{ steps.set_tag.outputs.IMAGE_VERSION }}
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - 
        name: Checkout other repo
        uses: actions/checkout@v2
        with:
          repository: tbuchi888/argocd_sample_repo
          path: argo_repo
      - 
        name: List files in the repository & sed TAG
        run: |
          echo "--- image ---"
          ls image/
          echo "--- argo_repo ---"
          ls argo_repo/
          sed -e "s/TAG/${{ github.sha }}/" argo_repo/manifests/deployment.yaml > argo_repo/k8s/bl.yml
          cat argo_repo/k8s/bl.yml
      -
        name: Commit files
        run: |
          cd argo_repo
          git config --local user.email "action@github.com"
          git config --local user.name "tbuchi888"
          git add .
          git commit -m "Add changes" -a
      - 
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: tbuchi888/argocd_sample_repo
          directory: argo_repo
          
